name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
          echo "Hello World!"
          echo "I was wondering to be happy"
          echo "Well just kidding"
      - name: Print GoodBye
        run: echo "Done - Bye!"
